### ISSUE TITLE
Adjust Max Zoom Generation?

### ISSUE THREAD

**Issue by Shadowfita** [jetelain/GameMapStorage#25]
Hi! Thank you so much for the work that has gone into these projects. It's very solid and works seamlessly. I have an Australian mirror running here: https://maps.a3wc.dev/ 

I was wondering if there was a way to adjust the maximum zoom that is used when generating a map with the extension? I have been able to work around this by using the 'maxZoom' and 'maxNativeZoom' props with leaflet, but was hoping that it was supported natively.

Thank you in advance!

**Comment by jetelain** [comment]
Hi,

You are right, the leaflet way is to have distinct values between 'maxZoom' and 'maxNativeZoom'. Provided script already add an extra zoom level for bitmap layers, and 3 for vector layers.

Having more bitmap layers would require much more storage, but it's not impossible. Recent maps have an extra zoom level compared to initial maps.

**Comment by Shadowfita** [comment]
Great to know, thanks so much for confirming! Just checking, there are no parameters in the map generation extension to adjust zoom-level, or it already generates a much better zoom than original altis, etc?

**Comment by jetelain** [comment]
The map generation extension already generates a much better zoom. No specific configuration is required.

I'm also working on vector / SVG maps for better zoom experience. It's been tested on Ivanivokova: 
https://atlas.plan-ops.fr/maps/arma3/ivanivokova/164?x=12847&y=14044&w=4822&h=2382

I will make it available on most maps in the coming weeks.

**Comment by Shadowfita** [comment]
Wow! Thats amazing. Thank you for your continued work on this!
